authorsId/urls.py
# This file is part of the authorsID project
#
# authorsID is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""authorsID URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin

from retrieval import urls as retrieval_urls
from retrieval import views as retrieval_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', retrieval_views.home, name='home'),
    url(r'^retrieval/', include(retrieval_urls))
]

retrieval/urls.py
# This file is part of the authorsID project
#
# authorsID is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url

from . import views

app_name = 'retrieval'
urlpatterns = [
    url(r'^article_input/$', views.ArticleFormView.as_view(), name='article_input'),
    url(r'^batch_input/$', views.ArticleBatchView.as_view(), name='batch_input'),
    url(r'^results/(?P<pk>[0-9]+)/$', views.ResultsSingleView.as_view(), name='results_single'),
    url(r'^map/$', views.map_view, name='map'),
    url(r'^search/$', views.search, name='search'),
    url(r'^batch_handle/$', views.batch_handle, name='batch_handle'),
    url(r'^download_stats/$', views.download_statistics, name='download_statistics'),
    url(r'^download_kml/$', views.download_kml, name='download_kml'),
    url(r'^progress/$', views.progress, name='progress')
]

retrieval/models.py
# This file is part of the authorsID project
#
# authorsID is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.contrib.gis.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone


class Affiliation(models.Model):
    name = models.TextField('Name')
    location = models.PointField('Location', null=True, geography=True)
    insertion_date = models.DateTimeField('Insertion date', default=timezone.now, null=False)
    aff_valid = models.BooleanField('Affiliation valid', default=False, null=False)

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.TextField('Name')
    email = models.EmailField('Email', null=True, max_length=1000)
    affiliation = models.ForeignKey(Affiliation, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    url = models.URLField('URL', default='', max_length=1000)
    title = models.TextField('Title', default='')
    authors = models.ManyToManyField(Author)
    journal = models.TextField('Journal', default='', null=True)
    publisher = models.TextField('Publisher', null=True)
    publication_date = models.TextField('Publication date', null=True)

    def __str__(self):
        return str(self.pk) + ' - ' + str(self.title)

    def get_absolute_url(self):
        return reverse('retrieval:results', kwargs={'pk': self.pk})

retrieval/forms.py
# This file is part of the authorsID project
#
# authorsID is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django import forms


class ArticleUrlForm(forms.Form):
    url = forms.URLField(label='URL', required=True, strip=True,
                         widget=forms.URLInput(attrs={'placeholder': 'Article URL'}))


class ArticleBatchForm(forms.Form):
    file = forms.FileField()

retrieval/views.py
# This file is part of the authorsID project
#
# authorsID is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json
import os
import tempfile
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.views import generic

from retrieval.forms import ArticleUrlForm, ArticleBatchForm
from .handlers import FileHandler, ArticleHandler
from .models import Article

handler = None


# Create your views here.
class ArticleFormView(generic.FormView):
    form_class = ArticleUrlForm
    template_name = 'retrieval/article_form.html'
    success_url = reverse_lazy('retrieval:search')

    def form_valid(self, form):
        data = form.cleaned_data
        super(ArticleFormView, self).form_valid(form)


class ResultsSingleView(generic.DetailView):
    model = Article
    template_name = 'retrieval/results_single.html'


class ArticleBatchView(generic.FormView):
    form_class = ArticleBatchForm
    template_name = 'retrieval/article_batch_form.html'
    success_url = reverse_lazy('retrieval:batch_handle')


def home(request):
    return render(request, 'retrieval/home.html')


def search(request):
    if request.method == 'POST':
        url = request.POST['url']
    else:
        url = ''
    if url == '':
        return HttpResponseRedirect(reverse_lazy('retrieval:results_single', args=(0,)))
    print(url)
    article = Article.objects.filter(url=url.lower())
    if article:
        return HttpResponseRedirect(reverse_lazy('retrieval:results_single', args=(article[0].pk,)))
    art_handler = ArticleHandler(url)
    article = art_handler.craft_article()
    return HttpResponseRedirect(reverse_lazy('retrieval:results_single', args=(article.pk,)))


def map_view(request):
    articles = request.session.get('articles')
    context = {'articles': articles}
    return render(request, 'retrieval/map.html', context)


def download_statistics(request):
    file_string = request.session.get('string')
    response = HttpResponse(file_string)
    response['Content-Disposition'] = 'attachment; filename="results.txt"'
    return response


def download_kml(request):
    file_kml = request.session.get('kml')
    response = HttpResponse(file_kml)
    response['Content-Disposition'] = 'attachment; filename="map.kml"'
    return response


def progress(request):
    if request.is_ajax():
        if handler is not None:
            perc = {'perc': handler.curr_percentage}
            return HttpResponse(json.dumps(perc), content_type='application/json')
        else:
            retn = {'err': None}
            return HttpResponse(json.dumps(retn), content_type='application/json')
    else:
        return HttpResponse()


def batch_handle(request):
    global handler
    handler = None
    file = tempfile.NamedTemporaryFile(delete=False)
    for line in request.FILES['file']:
        file.write(line)
    file_name = file.name
    file.close()
    handler = FileHandler(file_name)
    results = handler.craft_result()
    os.remove(file_name)
    request.session['string'] = results['string']  # Complete text generated for input sent
    request.session['articles'] = results['articles']  # List of articles, each with list of authors
    request.session['kml'] = results['kml']  # KML file generated
    return redirect(reverse_lazy('retrieval:map'))

retrieval/templates/retrieval/article_batch_form.html
<!--
    This file is part of the authorsID project

    authorsID is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

{% extends 'retrieval/base.html' %}
{% block header_title %}Article batch input{% endblock %}
{% block script %}
<script>
    function updateProgressBar() {
        $.ajax({
            url: "{% url 'retrieval:progress' %}",
            datatype: 'json',
            type: 'GET',
            success: function(data) {
                perc = data.perc;
                $("#id_progress").css("width", perc + "%").attr("aria-valuenow", perc).text(perc + "%");
            },
            error: function(error) {
                console.log("AJAX request failed");
            }
        });
    }
    $(document).ready(function () {
       $("#id_form").on("submit", function () {
           $(".progress").css("visibility", "visible");
           setInterval(updateProgressBar, 1000);
       });
    });

</script>
{% endblock %}
{% block body_centre %}
<h3 id="id_batch_title">Faça upload de um arquivo com vários artigos</h3>
<form action="{% url 'retrieval:batch_handle' %}" method="post" enctype="multipart/form-data" id="id_form">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send" id="id_send"/>
</form>
<div class="progress" style="margin-top: 25px; visibility: hidden">
    <div id="id_progress" class="progress-bar progress-bar-striped active" role="progressbar"
         aria-valuenow="00" aria-valuemin="0" aria-valuemax="100" style="width: 00%">
        0%
    </div>
</div>
{% endblock %}

retrieval/templates/retrieval/article_form.html
<!--
    This file is part of the authorsID project

    authorsID is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

{% extends 'retrieval/base.html' %}
{% block header_title %}Authors retrieval{% endblock %}
{% block body_centre %}
<h3 id="id_title">Insira aqui o link de um artigo publicado</h3>
<form action="{% url 'retrieval:search' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Send" id="id_send"/></p>
</form>
{% endblock %}

retrieval/templates/retrieval/base.html
<!--
    This file is part of the authorsID project

    authorsID is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--<meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">-->
    <meta name="viewport" content="initial-scale=1.0, width=device-width">
    <title>{% block header_title %}{% endblock %}</title>
    <link href="{% static 'retrieval/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'retrieval/jquery/jquery-3.0.0.js' %}"></script>
    {% block style %}
    {% endblock %}
    {% block script %}
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="text-center">
                <a href="http://www.gnu.org/licenses/">
                    <img src="http://www.gnu.org/graphics/agplv3-155x51.png" alt="[GNU AGPLv3 Logo]"/>
                </a>
                <h1 id="jumbotron">Identificação de autores</h1>
                {% block body_centre %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>
{% block map %}
{% endblock %}
</body>
</html>

retrieval/templates/retrieval/home.html
<!--
    This file is part of the authorsID project

    authorsID is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

{% extends 'retrieval/base.html' %}

{% block header_title %}Start Page{% endblock %}

{% block script %}
<!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
<script type="text/javascript">
    window.cookieconsent_options = {"message":"Esse website utiliza cookies para lhe garantir a melhor experiência possível, caso continue a utilizá-lo, você concorda com essa política.","dismiss":"Entendi!","learnMore":"Mais informações","link":null,"theme":"dark-bottom"};

</script>
<script type="text/javascript"
        src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
<!-- End Cookie Consent plugin -->
{% endblock %}

{% block body_centre %}
<a href="{% url 'retrieval:article_input' %}" class="jumbotron btn">Clique aqui para enviar um artigo</a>
<a href="{% url 'retrieval:batch_input' %}" class="jumbotron btn">Clique aqui para enviar vários artigos</a>
{% endblock %}

retrieval/templates/retrieval/map.html
<!--
    This file is part of the authorsID project

    authorsID is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

{% extends 'retrieval/base.html' %}
{% load retrieval_filters %}
{% block header_title %}Mapa{% endblock %}
{% block style %}
<style type="text/css">
      html, body { height: 100%; margin: 0; padding: 0; }
      #map { height: 100%; }

</style>
{% endblock %}
{% block body_centre %}
<a href="{% url 'retrieval:download_statistics' %}">Download file with detailed information</a>
<a href="{% url 'retrieval:download_kml' %}">Download KML generated file</a>
{% endblock %}
{% block map %}
<div id="map"></div>
<script>
        //TODO: Try to send this code to separate .js file
        var authAff = {};
        var delay = 400;
        var nextAddress = 0;
        var map;
        var bounds;
        var markerColour;

        function pinSymbol(color) {
            return {
                path: 'M 0,0 C -2,-20 -10,-22 -10,-30 A 10,10 0 1,1 10,-30 C 10,-22 2,-20 0,0 z M -2,-30 a 2,2 0 1,1 4,0 2,2 0 1,1 -4,0',
                fillColor: color,
                fillOpacity: 1,
                strokeColor: '#000',
                strokeWeight: 0.5,
                scale: 1
            };
        }

        function addMarker(auth, aff, lat, lng) {
            var contentString = '<b> Autor: </b>' + auth +
                '<br /> <b>Filiação:</b> ' + aff;
            var infoWindow = new google.maps.InfoWindow({
                content: contentString,
                maxWidth: 400
            });

            var marker = new google.maps.Marker({
                position: {lat: lat, lng: lng},
                map: map,
                animation: google.maps.Animation.DROP,
                title: auth,
                icon: pinSymbol(markerColour) // Change colour depending on article
            });

            bounds.extend(marker.position);
            map.fitBounds(bounds);
            google.maps.event.addListener(marker, "click", function() {
                infoWindow.open(map, marker);
                console.log('Marker ' + nextAddress + ' has been clicked!');
            });
        }

        function initMap() {
            var centerLatLng = {lat: 0.0, lng: 0.0};
            map = new google.maps.Map(document.getElementById('map'), {
                center: centerLatLng,
                zoom: 4,
                mapTypeId: google.maps.MapTypeId.HYBRID,
                tilt: 45
            });
            bounds = new google.maps.LatLngBounds();
            {% for authors in articles %}
                markerColour = '#' + Math.floor(Math.random()*16777215).toString(16);
                {% for author in authors %}
                    var aff = '{{ author.aff }}';
                    var auth = '{{ author.name }}';
                    var lat = {{ author.lat }};
                    var lng = {{ author.lng }};
                    var aff_valid ={{ author.aff_valid|yesno:"true,false" }};
                    console.log(aff_valid);

                    if(aff_valid == true) {
                        addMarker(auth, aff, lat, lng);
                    } else {
                        console.log("Affiliation invalid for author: " + auth);
                    }
                {% endfor %}
            {% endfor %}
            map.fitBounds(bounds);
            map.center(centerLatLng);
        }

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<INSERT-KEY-HERE>&callback=initMap&signed_in=true" async
        defer></script>
{% endblock %}

retrieval/templates/retrieval/results_single.html
<!--
    This file is part of the authorsID project

    authorsID is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

{% extends 'retrieval/base.html' %}

{% load retrieval_filters %}

{% block header_title %}Results{% endblock %}

{% block style %}
<style type="text/css">
      html, body { height: 100%; margin: 0; padding: 0; }
      #map { height: 50%; }

</style>
{% endblock %}

{% block body_centre %}
<h2 id="id_title_results">Resultados</h2>
<table class="table">
    <tr>
        <td class="article_title jumbotron">Título:</td>
    </tr>
    <tr>
        <td class="article_title">{{ article.title }}</td>
    </tr>
    <tr>
        <td class="jumbotron">Autores:</td>
    </tr>
    {% for author in article.authors.all %}
    <tr>
        <td class="author">{{ author }},
            {{ author.affiliation.name }}
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}
{% block map %}
<div id="map"></div>
<script>
        var authAff = {};
        var delay = 400;
        var nextAddress = 0;
        var map;
        var bounds;
        var markerColour = '#' + Math.floor(Math.random()*16777215).toString(16);

        function pinSymbol(color) {
            return {
                path: 'M 0,0 C -2,-20 -10,-22 -10,-30 A 10,10 0 1,1 10,-30 C 10,-22 2,-20 0,0 z M -2,-30 a 2,2 0 1,1 4,0 2,2 0 1,1 -4,0',
                fillColor: color,
                fillOpacity: 1,
                strokeColor: '#000',
                strokeWeight: 0.5,
                scale: 1
            };
        }

        function addMarker(auth, aff, lat, lng) {
            var contentString = '<b> Autor: </b>' + auth +
                '<br /> <b>Filiação:</b> ' + aff;
            var infoWindow = new google.maps.InfoWindow({
                content: contentString,
                maxWidth: 400
            });

            var marker = new google.maps.Marker({
                position: {lat: lat, lng: lng},
                map: map,
                animation: google.maps.Animation.DROP,
                title: auth,
                icon: pinSymbol(markerColour) // Change colour depending on article
            });

            bounds.extend(marker.position);
            map.fitBounds(bounds);
            google.maps.event.addListener(marker, "click", function() {
                infoWindow.open(map, marker);
                console.log('Marker ' + nextAddress + ' has been clicked!');
            });
        }

        function initMap() {
            var centerLatLng = {lat: 6.154370, lng: 21.024447};
            map = new google.maps.Map(document.getElementById('map'), {
                center: centerLatLng,
                zoom: 4,
                mapTypeId: google.maps.MapTypeId.HYBRID,
                tilt: 45
            });
            bounds = new google.maps.LatLngBounds();
            {% for author in article.authors.all %}
                var aff_valid = {{ author.affiliation.aff_valid|yesno:"true,false" }};
                console.log(aff_valid);
                var auth = '{{ author.name }}';
                if(aff_valid == true) {
                    addMarker(auth, '{{ author.affiliation.name }}', {{ author.affiliation.location|latitude }},
                        {{ author.affiliation.location|longitude }});
                } else {
                    console.log("Affiliation invalid for author: " + auth);
                }
            {% endfor %}
        };

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<INSERT-KEY-HERE>&callback=initMap&signed_in=true" async
        defer></script>
{% endblock %}